### ISSUE TITLE
Bug: Rendered HTML not indented correctly

### ISSUE THREAD

**Issue by paulrobertlloyd** [frctl/web-plugin#1]
I think this may be the right repo for this issue…

Is it possible to beautify rendered HTML markup? For example, should a component include another, the indentation is lost after the first line, e.g. this component markup:

<img width="500" alt="screen shot 2016-03-03 at 13 32 15" src="https://cloud.githubusercontent.com/assets/813383/13495876/09664fb0-e145-11e5-9765-25218ac3b4a5.png">

is rendered as:

<img width="500" alt="screen shot 2016-03-03 at 13 32 54" src="https://cloud.githubusercontent.com/assets/813383/13495889/17144694-e145-11e5-929c-e7b15d4f7103.png">

🙈

**Comment by allmarkedup** [comment]
Moving this issue to the main fractal repo.
